version: '3.8'

services:
  api:
    image: ${DOCKERHUB_USERNAME}/expenses_tracker:latest
    container_name: api
    networks:
      - common_network
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.prod
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 192M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - common_network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
        reservations:
          cpus: '0.05'
          memory: 16M
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - common_network

  migrations:
    container_name: migrations
    build: .
    command: ["/app/.venv/bin/alembic", "upgrade", "head"]
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - common_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot-www:/var/www/certbot
    depends_on:
      - api
    networks:
      - common_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: [
      "certonly",
      "--standalone",
      "--preferred-challenges", "http",
      "--email=${CERTBOT_EMAIL}",
      "--agree-tos",
      "--no-eff-email",
      "-d", "${DOMAIN}",
      "-d", "www.${DOMAIN}"
    ]
    env_file:
      - .env.prod

  certbot-renew:
    image: certbot/certbot
    container_name: certbot_renew
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot-www:/var/www/certbot
    entrypoint: sh -c "while :; do certbot renew --webroot -w /var/www/certbot && docker exec nginx_container nginx -s reload; sleep 12h; done"
    restart: unless-stopped
    networks:
      - common_network

networks:
  common_network:
    name: common_network
    driver: bridge

volumes:
  postgres:
    driver: local
    name: expenses_postgres_data
  certbot-etc:
  certbot-var:
