"""add last_refresh_jti to user model

Revision ID: 48571e41a89d
Revises: aa86c989cf0a
Create Date: 2025-09-22 19:03:04.897913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48571e41a89d"
down_revision: Union[str, Sequence[str], None] = "aa86c989cf0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_refresh_jti", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_refresh_jti")
    # ### end Alembic commands ###
