apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: GET

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance', 'container', 'service']
        mappedTags:
          - key: service
            value: service.name
          - key: container
            value: container.name
      tracesToMetrics:
        datasourceUid: prometheus
        tags: ['job', 'instance', 'container', 'service']

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"otelTraceID\":\\s*\"(\\w+)\""
          name: OtelTraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
